sudo: false
language: ruby
install:
  - git clone https://github.com/ruby/mspec.git ../mspec
before_install:
  # fix Travis trunk build as of 2018-01-05
  - |
    rv="$(ruby -e 'STDOUT.write RUBY_VERSION')";
    if [ "$rv" = "2.7.0" ]; then
      lib="$(ruby -e 'STDOUT.write RbConfig::CONFIG["sitelibdir"]')";
      echo "Processing 2.7.0 - $lib";
      rm -rf $lib/rubygems;
      rm -f  $lib/rubygems.rb $lib/ubygems.rb;
    fi
script:
  - ../mspec/bin/mspec $MSPEC_OPTS
matrix:
  include:
    - rvm: 2.5.3
      env: MSPEC_OPTS="-R2 -ff"
    - rvm: 2.3.8
    - rvm: 2.4.5
      env: CHECK_LEAKS=true
    - rvm: 2.5.3
      env: CHECK_LEAKS=true
    - rvm: 2.6.0
      env: CHECK_LEAKS=true
    - rvm: ruby-head
    - env: RUBOCOP=true
      rvm: 2.4.5
      script:
        - gem install rubocop:0.61.0
        - rubocop
  allow_failures:
    - rvm: ruby-head
branches:
  only:
    - master
    - /^try/
notifications:
  email:
    on_success: change
    on_failure: change
